import { SKILL_INVOKES } from "../../shared/skills/invokes";
import { CopyButton } from "../../shared/ui/copy-button";

const VERIFY_DISCOVERY = "In this Codex desktop session, discover the installed vl-orch-codex, vl-arch, vl-adhd and vl-present skills. Report the exact resolved source paths and their Codex support, invocation and prerequisites. Read/apply the full vl-adhd writing policy and vl-present presentation contract through supported $vl-adhd / $vl-present invocation or explicit resolved source fallback. Read the intended skill source and perform a read-only invocation check without seating another role or dispatching work. If missing, shadowed, stale or unsupported, stop and report the evidence; installation success alone is not discovery proof.";

export function CodexSetup() {
  return <section className="panel" id="codex-setup" data-host="codex">
    <h2>Install and verify Codex desktop skills</h2>
    <p>From the Vilya checkout, add the Codex target while preserving the Claude Code/Cursor default:</p>
    <pre>{"pwsh scripts/install-skills.ps1 -IncludeCodex\nbash scripts/install-skills.sh --include-codex"}</pre>
    <p>Codex uses <code>$HOME/.agents/skills</code>. The existing default remains <code>~/.claude/skills</code>; an explicit custom target takes precedence. Keep links pointing at the canonical source. Avoid duplicate or shadowing installations.</p>
    <p>To update verified whole-folder junctions, merge/pull the reviewed change into their canonical Vilya source, reload the session and read the resolved current SKILL.md plus <code>vl-orch-codex/references/model-routing.md</code>. Preserve and reconcile divergent copies before reinstalling. Install complete folders including references; a raw registry SKILL.md is not a complete bundle. Existing loaded instructions do not refresh merely because the source changed.</p>
    <p>Existing links reflect changed files after pull. Newly added folders such as vl-present require rerunning the installer with -IncludeCodex or --include-codex. Copies require the whole folder and resources. Refresh through a supported session surface and inspect both resolved shared contracts separately from installer/build success.</p>
    <h3>Discovery is a separate check</h3>
    <p>Open or refresh a Codex desktop session and inspect its available skills. Use the supported dollar invocation, such as <code>{SKILL_INVOKES.orchestratorCodex}</code>, or explicitly read and apply the resolved SKILL.md source when native invocation is unavailable. Check the skill detail page for applicability, prerequisites and host behavior before use.</p>
    <p>{VERIFY_DISCOVERY}</p><CopyButton text={VERIFY_DISCOVERY} />
    <p className="note">Record the actual discovered source, invocation result and session/tool context on the owning issue. Installer tests do not prove runtime discovery. The integrated discovery and full desktop acceptance evidence belongs to <a href="https://github.com/jerrodtuck/vilya/issues/329">#329</a>; do not call it verified from these instructions.</p>
    <h3>Prepare the repo and seats</h3>
    <p>Complete the shared per-repo board/config setup below. Read local rules and expose the required GitHub, skills, collaboration and managed-worktree tools. The orch owns planning; there is no standing Codex Planner to launch. Select GPT-6.1 Sol/high for the <a href="/architect?host=codex">architect</a> and GPT-6.1 Sol/medium for the <a href="/orch?host=codex">orch</a> before invoking their skills. Skill invocation cannot change an active chat&apos;s model or reasoning effort. Paste each trusted human entry prompt separately, identifying repo, board and counterpart. Each prompt includes standing permission to initiate and reply within that scope.</p>
    <h3>Configure phases before dispatch</h3>
    <p>Use the <a href="/orch?host=codex">model preference card</a> to authorize a phase policy or pin exact choices. This operator adopted the #357 Sol-first route on 2026-10-08: Sol/medium for normal planning, implementation and repair; Sol/high for difficult architecture and separate independent review; Luna/low ONLY for enumerated mechanical operations with objective verification; and Astra/high or justified xhigh only after a recorded Sol impasse or capability failure. Read and apply the full bundled routing/repair contract before phase selection, implementation, review, repair or resume. Route by uncertainty and consequence; small behavior changes are not eligible for Luna. At the second consecutive unsuccessful corrective change plus targeted verification of the same unresolved defect/gate, stop before a third correction and hand the durable ledger/HEAD/diff/ownership to orch planning. Initial failure is detection; reruns, renames, unrelated passes and resumes do not reset counts. Earlier hard stops apply. Record actual settings, attempts, review findings and observed elapsed/usage where available; unavailable usage is not zero. Validate exact model/reasoning combinations and context-fork restrictions against current capabilities; record phase, date, authorization source and override scope. Scoped choices win only within scope; preserve active and resumed worker pins. Other operators keep configured defaults without their own authorization. Ambiguous scope or unavailable combinations stop dispatch without silent substitution or effort increase. A settled plan carries decisions, ownership, constraints, verification and stop gates into implementation; medium effort never weakens checks. Surface more investigation or effort needs and return real forks to planning. Token reduction is a goal, not measured savings or a quality guarantee.</p>
    <h3>Requested sidebar workers</h3>
    <p>If you explicitly request new worker chats, the orch reuses or creates <code>&lt;repo-short&gt;-orch-working</code> and moves every created worker there before reporting dispatch complete. For Vilya: <code>vilya-orch-working</code>. It preserves project association and unrelated chats, verifies no duplicates and reports grouping failures with the created chat identifiers. Ordinary subagents are separate; grouping grants no permission or isolation.</p>
    <h3>Worktree setup, reporting and recovery</h3>
    <p>Choose an explicit verified starting ref, inspect managed attachments, and verify the assigned absolute checkout and branch before writing. Apply ignored-file prerequisites through the repo setup hook or <code>scripts/apply-worktreeinclude</code>; spawning alone does not copy setup or isolate the workspace. Preserve private files without exposing or staging them.</p>
    <p>Prefer <code>create_worktree</code> with the intended ref; await completion. Recover failed registration with <code>attach_worktree</code>, then verify <code>list_artifacts</code> in the owning orch chat. Record identity/path/branch/issue. Managed creation can start detached: explicitly create/check out the issue branch before writing, and pass absolute workdir to every chip command.</p>
    <p>Managed attachments, permanent worktree projects and sidebar chats are distinct. Subagent-created attachments belong to the top-level parent chat. Ordinary subagents require no separate sidebar chat or permanent project; new sidebar chats require an explicit human request. GUI visibility is a Codex product concern, not a Vilya acceptance requirement.</p>
    <p>Follow the <a href="/orch?host=codex#codex-dispatch-path">chip, active-turn wait, amendment, PR verification, interrupted recovery and archival cards</a>. Future wakeups require an explicitly requested automation. Use managed archival and verify attachment state; chat archival alone is not proof of cleanup.</p>
    <p><a href="/differences?host=codex">Evidence and host differences</a>{" · "}<a href="/skills">Every skill’s Codex applicability</a>{" · "}<a href="https://learn.chatgpt.com/docs/build-skills">Official skills documentation</a></p>
    <p>Codex desktop only. Codex CLI and a new Codex unattended backend are deferred. Existing night-shift remains <code>plan:ready ∧ night-shift:ready</code>.</p>
  </section>;
}
